### ISSUE TITLE
upgrade travis osx version

### ISSUE THREAD

**Issue by ebbit1q** [Cockatrice/Cockatrice#3456]
We currently build on el_capitan which since recently no longer gets binary packages for qt: [commit](https://github.com/Homebrew/homebrew-core/commit/5eb54ced793999e3dd3bce7c64c34e7ffe65ddfd)
We should consider upgrading to sierra, this would also mean we'd get bottled protobuf again (building protobuf from source on current builds takes >5 mins) [commit](https://github.com/Homebrew/homebrew-core/commit/29d15c71b1e6d56533e9fb2374d3df2c639681d7)
This would force people currently on this 3 year old version to upgrade to sierra if they don't want to build from source, in a similar fashion to how they'll have to build all the dependencies as well.
Also see my attempts at "saving" el_capitan: #3455 
And the directly related issue: #3450

**Comment by ebbit1q** [comment]
Additional benefits include using a new version of xcode and using a never image from travis that'll spend less time on the `brew update` command (currently clocking at 4 mins)

**Comment by tooomm** [comment]
Note: when we update the `xcode` image at travis (to `xcode9.2` with osx 10.12 for example), a bottle for protobuf would be available again, but with the python flag it'll still build from source... so we would need to unlike python first and install normally like this:

```
      - brew unlink python
      - brew install protobuf
```

The mac section in .travis.yml would look like this right now:

```
  #macOS
  - name: macOS (Debug)
    if: tag IS NOT present
    os: osx
    osx_image: xcode9.2
    cache: ccache
    before_install:
      - brew update
      - brew install ccache
      - brew unlink python
      - brew install protobuf
      - brew install qt
    script: bash ./.ci/travis-compile.sh --server --install --debug

  - name: macOS (Release)
    if: (branch = master AND NOT type = pull_request) OR tag IS present
    os: osx
    osx_image: xcode9.2
    cache: ccache
    before_install:
      - brew update
      - brew install ccache
      - brew unlink python
      - brew install protobuf
      - brew install qt
    script: bash ./.ci/travis-compile.sh --server --package "$TRAVIS_OS_NAME" --release
```
